import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainPageNav from "../nav/main_page_nav";
import Footer from "../footer/footer";
import Header from "../nav/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="ABi5tu30kKpHJMlDdhW71AwFIggm8tsK2VFLhqw9F-8" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="main_page">
          <MainPageNav />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
